#! /bin/sh

# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
print_info() {
    info "💻 Host" model
    info "🤟 Distro" distro
    info "🐧 Kernel" kernel
    info "🐚 Shell" shell
    info "⛩️ WM" wm
    info "🌸 Theme" theme
    info "🌱 Icons" icons
    info "🐱 Term" term
    info "⌨️ Font" font
    info "📦 Packages" packages
    info "🎶" song

    info cols
}

# Show/Hide OS Architecture.
os_arch="off"

# Shorten the output of the uptime function
uptime_shorthand="tiny"

# Show/Hide Package Manager names.
package_managers="on"

# Shorten output of GTK Theme / Icons / Font
gtk_shorthand="on"
gtk2="off"
gtk3="on"

# Format to display song information.
song_format="%artist% - %album% - %title%"

# Print the Artist, Album and Title on separate lines
song_shorthand="off"

# 'mpc' arguments (specify a host, password etc).
# Example: mpc_args=(-h HOST -P PASSWORD)
mpc_args=()

# Progress bar length in spaces
# Number of chars long to make the progress bars.
bar_length=15

# Progress bar colors
# When set to distro, uses your distro's logo colors.
# Values:   'distro', 'num'
bar_color_elapsed="distro"
bar_color_total="distro"

# Crop mode
# Values:   'normal', 'fit', 'fill'
crop_mode="normal"
image_size="300px"
gap=3
yoffset=0
xoffset=0
background_color=""

# Image backend.
image_backend="kitty"

# Thumbnail directory
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"

# Image Source
image_source=$(
    ls ~/.config/neofetch/imgs | sort -R | while read file; do
        echo "${HOME}/.config/neofetch/imgs/${file}"
        break
    done
)
